// Copyright 2025 Chisomo Makombo Sakala
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
use clap::Parser;
use clap::Subcommand;
use std::io::ErrorKind;
use std::path::Path;
use std::path::PathBuf;

use crate::config::Tasks;
use crate::error::ConfigError;

/// Algorithm Benchmarking Orchestrator
#[derive(Debug, Parser)]
#[command(version, about = "Algorithm Benchmarking Orchestrator")]
pub struct Cli {
  #[command(subcommand)]
  pub command: Commands,
}

/// Defines the main subcommands: `build` and `run`.
#[derive(Debug, Subcommand)]
pub enum Commands {
  /// Scans the components directory and builds all found components.
  Build {
    /// Root directory containing component subdirectories.
    #[arg(long, default_value = ".")]
    components_dir: PathBuf,

    #[command(flatten)]
    manifest: ManifestArgs,

    #[command(flatten)]
    filter_args: FilterArgs,
  },

  /// Runs the benchmark using built components.
  Run(RunArgs),
}

#[derive(Debug, clap::Args)]
pub struct FilterArgs {
  #[arg(long, value_delimiter = ',')]
  pub include: Option<Vec<String>>,

  #[arg(long, conflicts_with = "include", value_delimiter = ',')]
  pub exclude: Option<Vec<String>>,
}

impl RunArgs {
  fn parse_tasks(s: &str) -> Result<Tasks, ConfigError> {
    serde_json::from_str(s).map_err(ConfigError::ParseTasksJson)
  }
}
/// Arguments for the `run` subcommand.
#[derive(Debug, clap::Args)]
pub struct RunArgs<F: FileReader + Default + std::fmt::Debug = RealFileSystem> {
  /// JSON string mapping languages to lists of algorithm names to run.
  /// Example: '{"cpp": ["std::sort"], "lean": ["List.mergeSort"]}'
  #[arg(long, required = true, value_parser = RunArgs::parse_tasks)]
  pub tasks: Tasks,

  #[command(flatten)]
  pub manifest: ManifestArgs<F>,

  #[command(flatten)]
  pub generator: GenArgs,
}

#[derive(Debug, clap::Args)]
pub struct GenArgs {
  /// Name of the generator component to use, or 'none' for self-contained algorithms.
  #[arg(id = "generator", long, required = true)]
  pub name: String,
  /// Seed for the random number generator (if a generator is used).
  #[arg(long, requires = "generator")]
  pub seed: Option<u64>,
  // --- Passthrough Arguments ---
  /// All remaining arguments are passed to the data generator.
  #[arg(
    trailing_var_arg = true,
    allow_hyphen_values = true,
    requires = "generator"
  )]
  pub trailing_args: Vec<String>,
}

#[derive(Debug, clap::Args, Default)]
pub struct ManifestArgs<F: FileReader + Default + std::fmt::Debug = RealFileSystem> {
  /// Output path for the build manifest.
  /// Path to the build manifest (generated by the 'build' command).
  #[arg(id = "root-dir", long, default_value = ".")]
  pub root_dir: PathBuf,

  #[arg(id = "manifest-filename", long)]
  pub file_path: Option<PathBuf>,

  /// JSON map that Override components in manifest file.
  #[arg(id = "component-overrides", long)]
  pub overrides: Option<String>,

  #[arg(skip)]
  pub file_reader: F,
}

impl<F: FileReader + Default + std::fmt::Debug> ManifestArgs<F> {
  pub fn get_path(&self) -> PathBuf {
    let default = PathBuf::from("impa_manifest.json");
    self
      .root_dir
      .join(self.file_path.as_ref().unwrap_or(&default))
  }

  pub fn get_content(&self) -> Result<Option<String>, ConfigError> {
    let path = &self.get_path();
    self
      .file_reader
      .read_to_string(path)
      .map_err(|e| ConfigError::ReadManifest {
        path: path.to_owned(),
        source: e,
      })
  }
}

pub trait FileReader {
  fn read_to_string(&self, path: &Path) -> std::io::Result<Option<String>>;
}

#[derive(Default, Debug)]
pub struct RealFileSystem;

impl FileReader for RealFileSystem {
  fn read_to_string(&self, path: &Path) -> std::io::Result<Option<String>> {
    match std::fs::read_to_string(path) {
      Ok(contents) => Ok(Some(contents)),
      Err(e) if e.kind() == ErrorKind::NotFound => Ok(None),
      Err(e) => Err(e),
    }
  }
}
