use clap::Parser;
use clap::Subcommand;
use std::path::PathBuf;

#[derive(Debug, Parser)]
#[command(version, about = "Algorithm Benchmarking Orchestrator")]
pub struct Cli {
  #[command(subcommand)]
  pub command: Commands,
}

#[derive(Debug, Subcommand)]
pub enum Commands {
  /// Scans the components directory and builds all found components.
  Build {
    /// Root directory containing component subdirectories.
    #[arg(long, default_value = ".")]
    components_dir: PathBuf,

    /// Output path for the build manifest.
    #[arg(long, default_value = "impa_manifest.json")]
    manifest_path: PathBuf,
  },

  /// Runs the benchmark using built components.
  Run(RunArgs),
}

#[derive(Debug, clap::Args)]
pub struct RunArgs {
  /// JSON string mapping languages to lists of algorithm names to run.
  /// Example: '{"cpp": ["std::sort"], "lean": ["List.mergeSort"]}'
  #[arg(long, required = true)]
  pub algorithms: String,

  /// Seed for the random number generator (if a generator is used).
  #[arg(long)]
  pub seed: Option<u64>,

  /// Name of the generator component to use, or 'none' for self-contained algorithms.
  #[arg(long, required = true)]
  pub generator: String,

  // --- High-Priority Overrides ---
  /// Override the path to the generator executable.
  #[arg(long)]
  pub generator_override_path: Option<PathBuf>,

  /// Override paths to algorithm executables as a JSON map.
  /// Example: '{"cpp": "./my_cpp_exe", "lean": "./my_lean_exe"}'
  #[arg(long)]
  pub algorithm_override_paths: Option<String>,

  /// Path to the build manifest (generated by the 'build' command).
  #[arg(long, default_value = "impa_manifest.json")]
  pub manifest_path: PathBuf,

  // --- Passthrough Arguments ---
  /// All remaining arguments are passed to the data generator.
  #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
  pub generator_args: Vec<String>,
}
